var namespaceATAS_1_1DataFeedsCore_1_1Statistics =
[
    [ "AvgLossParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1AvgLossParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1AvgLossParameter" ],
    [ "AvgPnLParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1AvgPnLParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1AvgPnLParameter" ],
    [ "AvgProfitParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1AvgProfitParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1AvgProfitParameter" ],
    [ "CommissionParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1CommissionParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1CommissionParameter" ],
    [ "IStatisticsParameterGroup", "interfaceATAS_1_1DataFeedsCore_1_1Statistics_1_1IStatisticsParameterGroup.html", "interfaceATAS_1_1DataFeedsCore_1_1Statistics_1_1IStatisticsParameterGroup" ],
    [ "ITradingStatistics", "interfaceATAS_1_1DataFeedsCore_1_1Statistics_1_1ITradingStatistics.html", "interfaceATAS_1_1DataFeedsCore_1_1Statistics_1_1ITradingStatistics" ],
    [ "ITradingStatisticsProvider", "interfaceATAS_1_1DataFeedsCore_1_1Statistics_1_1ITradingStatisticsProvider.html", "interfaceATAS_1_1DataFeedsCore_1_1Statistics_1_1ITradingStatisticsProvider" ],
    [ "LossDaysParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1LossDaysParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1LossDaysParameter" ],
    [ "LossPnLParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1LossPnLParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1LossPnLParameter" ],
    [ "LossTradesParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1LossTradesParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1LossTradesParameter" ],
    [ "MaxDrawdownParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1MaxDrawdownParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1MaxDrawdownParameter" ],
    [ "MaxRelativeDrawdownParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1MaxRelativeDrawdownParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1MaxRelativeDrawdownParameter" ],
    [ "MyTradeQueue", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1MyTradeQueue.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1MyTradeQueue" ],
    [ "ProfitDaysParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitDaysParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitDaysParameter" ],
    [ "ProfitFactorParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitFactorParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitFactorParameter" ],
    [ "ProfitPnLParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitPnLParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitPnLParameter" ],
    [ "ProfitTradesParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitTradesParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1ProfitTradesParameter" ],
    [ "RecoveryFactorParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1RecoveryFactorParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1RecoveryFactorParameter" ],
    [ "StatisticsManager", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1StatisticsManager.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1StatisticsManager" ],
    [ "StatisticsParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1StatisticsParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1StatisticsParameter" ],
    [ "StatisticsParameterGroup", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1StatisticsParameterGroup.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1StatisticsParameterGroup" ],
    [ "TotalDaysParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TotalDaysParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TotalDaysParameter" ],
    [ "TotalPnLParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TotalPnLParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TotalPnLParameter" ],
    [ "TotalTradesParameter", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TotalTradesParameter.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TotalTradesParameter" ],
    [ "TradingStatistics", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TradingStatistics.html", "classATAS_1_1DataFeedsCore_1_1Statistics_1_1TradingStatistics" ],
    [ "PnlTuple", "namespaceATAS_1_1DataFeedsCore_1_1Statistics.html#acd25abcdcc09b4b77eb5c940901aea75", null ],
    [ "EquityValue", "namespaceATAS_1_1DataFeedsCore_1_1Statistics.html#a38271fe8706f1b9675f22ad2d2cf845f", null ]
];